# Viscript's configuration file that contains apps and other settings

# Available applications
apps:
  # skycoin:
  #   path: /bin/skycoin/skycoin
  #   args:
  #     - --gui-dir=/bin/skycoin/static/
  #   desc: Skycoin main binary
  # skycoin-cli:
  #   path: /bin/skycoin/skycoin-cli
  #   args:
  #   desc: Skycoin command line interface
  # meshnet-server:
  #   path: /bin/meshnet/meshnet-server
  #   args:
  #   desc: Meshnet nodes manager server
  # meshnet-cli:
  #   path: /bin/meshnet/meshnet-cli
  #   args:
  #   desc: Command line client for meshnet nodes manager server
  meshnet-nm:
    path: bin/meshnet/meshnet-run-nm
    args: 
      - 0.0.0.0:5999         # host:port for control messages exchange
    desc: Run meshnet node manager
    help: |
      # TODO: write meshnet nm help
  meshnet-node:
    path: bin/meshnet/meshnet-run-node
    args:
      - 111.222.123.44:5000 # host:port for control messages exchange
      - 202.101.65.43:5999  # nodemanager external address for control messages
      - true                # if the node needs to be connected randomly
      - 15000               # tcp port at which node will listen app messages
    desc: Run meshnet node
    help: |
      # TODO: write meshnet node help
  meshnet-socks-client:
    path: bin/meshnet/meshnet-run-socks-client
    args: 
      - sockscli            # text name of app, must be unique 
      - 101.202.34.56:15000 # node host:port which app will be talked with
      - 8000                # port which socks will listen for web app messages
    desc: Run meshnet socks client
    help: |
      # TODO: write socks client help
  meshnet-socks-server:
    path: bin/meshnet/meshnet-run-socks-server
    args:
      - sockssrv            # text name of app, must be unique
      - 101.202.34.56:15000 # node host:port which app will be talked with
      - 8001                # port which socks server use for conn target host
    desc: Run meshnet socks server
    help: |
      # TODO: write socks server help
  meshnet-vpn-client:
    path: bin/meshnet/meshnet-run-vpn-client
    args:
      - vpncli              # text name of app, must be unique
      - 101.202.34.56:15000 # node host:port which app will be talked with
      - 8000                # port which vpn will listen for web app in messages
    desc: Run meshnet vpn client
    help: |
      # TODO: write vpn client help
  meshnet-vpn-server:
    path: bin/meshnet/meshnet-run-vpn-server
    args:
      - vpnsrv              # text name of app, must be unique
      - 101.202.34.56:15000 # node host:port which app will be talked with
    desc: Run meshnet vpn server
    help: |
      # TODO: write vpn server help
# Additional settings
settings:
  verboseInput: false   # Will print key and mouse input if set to true
  verifyParsingByPrinting: true  # Will print this file's contents
