# Viscript's configuration file that contains apps and other settings

# Available applications
apps:
  skycoin:
    path: /bin/skycoin/skycoin
    args:
      - --gui-dir=/bin/skycoin/static/
    desc: Skycoin main binary
  skycoin-cli:
    path: /bin/skycoin/skycoin-cli
    args: 
    desc: Skycoin command line interface
  meshnet-server:
    path: /bin/meshnet/meshnet-server
    args: 
    desc: Meshnet nodes manager server
  meshnet-cli:
    path: /bin/meshnet/meshnet-cli
    args:
    desc: Command line client for meshnet nodes manager server
  meshnet-nm:
    path: /bin/meshnet/meshnet-run-nm
    args:
    desc: Run meshnet node manager
  meshnet-node:
    path: /bin/meshnet/meshnet-run-node
    args:
    desc: Run meshnet node
  meshnet-socks-client:
    path: /bin/meshnet/meshnet-run-socks-client
    args:
    desc: Run meshnet socks client
  meshnet-socks-server:
    path: /bin/meshnet/meshnet-run-socks-server
    args:
    desc: Run meshnet socks server
  meshnet-vpn-client:
    path: /bin/meshnet/meshnet-run-vpn-client
    args:
    desc: Run meshnet vpn client
  meshnet-vpn-server:
    path: /bin/meshnet/meshnet-run-vpn-server
    args:
    desc: Run meshnet vpn server

# Additional settings
settings:
  verboseInput: false   # Will print key and mouse input if set to true
  verifyParsingByPrinting: false  # Will print this file's contents
